/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-12-23 16:48:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.job;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/Users/hayeonkim/_spring_workspace/_final_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/finalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1696436773334L));
    _jspx_dependants.put("jar:file:/Users/hayeonkim/_spring_workspace/_final_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/finalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/Users/hayeonkim/_spring_workspace/_final_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/finalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>job list page</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/page.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/jobListPage.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/mainFloatingMenu.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<!-- 메인 이벤트 페이지 -->\n");
      out.write("<div class=\"jobListPart\">\n");
      out.write("	<img alt=\"\" src=\"../resources/image/albacado.png\">\n");
      out.write("	<div class=\"jobListPartSub\">\n");
      out.write("		<h3>우리동네에서 찾는 알바카도</h3>\n");
      out.write("		<a href=\"/job/register\" ><button type=\"button\" class=\"\">공고 올리기</button></a>\n");
      out.write("		<a href=\"/job/about\" ><button type=\"button\" class=\"\" >알바카도 활용법</button></a>\n");
      out.write("		<a href=\"/myList/likeList\" ><button type=\"button\" class=\"\">관심 목록</button></a>\n");
      out.write("		<a href=\"/myList/commuList\" ><button type=\"button\" class=\"\">동네생활</button></a>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("   <div id=\"loading\">\n");
      out.write("      <!-- 로딩페이지 -->\n");
      out.write("   </div>\n");
      out.write("<div class=\"bodyContainer\">\n");
      out.write("   	<!-- 검색라인 추가가능하면 추가 -->\n");
      out.write("      \n");
      out.write("\n");
      out.write("	\n");
      out.write(" \n");
      out.write("	<!-- 우리동네 알바 출력 리스트 -->\n");
      out.write("	<div class=\"titleLine\">\n");
      out.write("	<h3>우리동네 알바</h3>\n");
      out.write("	 	<section>\n");
      out.write("			<div class=\"allMenu\">\n");
      out.write("				<select class=\"menuSelect\" id=\"menuSelect\" name=\"menuSelect\">\n");
      out.write("					<option >전체</option>\n");
      out.write("					<option value=\"food\">외식.음료</option>\n");
      out.write("					<option value=\"shop\">매장관리.판매</option>\n");
      out.write("					<option value=\"service\">서비스</option>\n");
      out.write("					<option value=\"office\">사무직</option>\n");
      out.write("					<option value=\"product\">생산.건설</option>\n");
      out.write("					<option value=\"driver\">운전.배달</option>\n");
      out.write("					<option value=\"education\">교육.강사</option>\n");
      out.write("			        <option value=\"etc\">기타</option>\n");
      out.write("				</select>\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			<select id=\"sortSelect\" class=\"sortSelect\" name=\"sortSelect\">\n");
      out.write("			    <option value=\"newest\" >최신순</option>\n");
      out.write("			    <option value=\"oldest\">오래된 순</option>\n");
      out.write("			    <option value=\"hotest\">인기순</option>\n");
      out.write("			</select>\n");
      out.write("	 	</section>\n");
      out.write("	</div>                                                                                                                                                                                                                                                                                                                                                                                                   \n");
      out.write("\n");
      out.write("	<div class=\"brdListArea\" id=\"moreJobArea\">\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	<button type=\"button\" id=\"moreBtn\" onclick=\"loadMore()\">더 보기</button>\n");
      out.write("	\n");
      out.write("</div>\n");
      out.write("<script src=\"/resources/js/jobBoardList.js\"></script>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
