/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-12-23 13:19:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1696436773334L));
    _jspx_dependants.put("jar:file:/Users/hayeonkim/_spring_workspace/_final_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/finalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Avocart</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/index.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./common/header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<!-- 배너 -->\n");
      out.write("<div id=\"carouselExample\" class=\"carousel slide\" data-bs-ride=\"carousel\">\n");
      out.write("  <div class=\"carousel-inner\">\n");
      out.write("  	<!-- 1 -->\n");
      out.write("    <div class=\"carousel-item active\">\n");
      out.write("    <a href=\"/joongo/list\">\n");
      out.write("      <img src=\"/resources/image/bannerTest1.jpg\" class=\"d-block w-100 bannerImgs\" alt=\"...\">\n");
      out.write("    </a>\n");
      out.write("    </div>\n");
      out.write("  	<!-- 2 -->\n");
      out.write("    <div class=\"carousel-item\">\n");
      out.write("    <a href=\"/store/list\">\n");
      out.write("      <img src=\"/resources/image/bannerTest2.png\" class=\"d-block w-100 bannerImgs\" alt=\"...\">\n");
      out.write("    </a>\n");
      out.write("    </div>\n");
      out.write("  	<!-- 3 -->\n");
      out.write("    <div class=\"carousel-item\">\n");
      out.write("    <a href=\"/job/list\">\n");
      out.write("      <img src=\"/resources/image/bannerTest3.png\" class=\"d-block w-100 bannerImgs\" alt=\"...\">\n");
      out.write("    </a>\n");
      out.write("    </div>\n");
      out.write("  	<!-- 4 -->\n");
      out.write("    <div class=\"carousel-item\">\n");
      out.write("    <a href=\"/community/list\">\n");
      out.write("      <img src=\"/resources/image/bannerTest4.jpg\" class=\"d-block w-100 bannerImgs\" alt=\"...\">\n");
      out.write("    </a>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <button class=\"carousel-control-prev\" id=\"bannerPrevBtn\" type=\"button\" data-bs-target=\"#carouselExample\" data-bs-slide=\"prev\">\n");
      out.write("    <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\n");
      out.write("    <span class=\"visually-hidden\">Previous</span>\n");
      out.write("  </button>\n");
      out.write("  <button class=\"carousel-control-next\" id=\"bannerNextBtn\" type=\"button\" data-bs-target=\"#carouselExample\" data-bs-slide=\"next\">\n");
      out.write("    <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\n");
      out.write("    <span class=\"visually-hidden\">Next</span>\n");
      out.write("  </button>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- bodyContainer 1 -->\n");
      out.write("<div class=\"bodyContainer\">\n");
      out.write("<!-- 로딩페이지 -->\n");
      out.write("<div id=\"loading\"></div>\n");
      out.write("\n");
      out.write("<!-- 중고라인 -->\n");
      out.write("<div class=\"boardListLine firstJoongoLine\">\n");
      out.write("	<div class=\"ListLineTop\">\n");
      out.write("		<p>방금 등록된 상품</p>\n");
      out.write("		<a href=\"/joongo/list\">더보기</a>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"ListLineMiddle\" id=\"joongoMiddle\">\n");
      out.write("		<div class=\"joongo_item\">\n");
      out.write("			<a href=\"#\">\n");
      out.write("				<img alt=\"\" src=\"\">\n");
      out.write("				<div class=\"joongo_item_detail\">\n");
      out.write("					<p>폴로 반팔 티셔츠</p>\n");
      out.write("					<p>9,000원</p>\n");
      out.write("					<p>구월동 | 2023-12-19</p>\n");
      out.write("				</div>\n");
      out.write("			</a>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"boardListLine\">\n");
      out.write("	<div class=\"ListLineTop\">\n");
      out.write("		<p>실시간 인기 상품</p>\n");
      out.write("		<a href=\"/joongo/list\">더보기</a>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"ListLineMiddle\" id=\"joongoLikeMiddle\">\n");
      out.write("		<div class=\"joongo_item\">\n");
      out.write("			<a href=\"#\">\n");
      out.write("				<img alt=\"\" src=\"\">\n");
      out.write("				<div class=\"joongo_item_detail\">\n");
      out.write("					<p>폴로 반팔 티셔츠</p>\n");
      out.write("					<p>9,000원</p>\n");
      out.write("					<p>구월동 | 2023-12-19</p>\n");
      out.write("				</div>\n");
      out.write("			</a>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- 버튼들 -->\n");
      out.write("<div class=\"boardListLine\">\n");
      out.write("	<div class=\"ListLineTop\">\n");
      out.write("		<p>거래되는 품목</p>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"ListLineMiddle\">\n");
      out.write("		<div class=\"joongoMenuBox\">\n");
      out.write("			<button class=\"joongoMenuBtn menuBtn\">\n");
      out.write("				<img alt=\"\" src=\"/resources/image/macbook.png\" class=\"menuBtn\">\n");
      out.write("			</button>\n");
      out.write("			<p>디지털기기</p>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"joongoMenuBox\">\n");
      out.write("			<button class=\"joongoMenuBtn menuBtn\">\n");
      out.write("				<img alt=\"\" src=\"/resources/image/sofa.png\" class=\"menuBtn\">\n");
      out.write("			</button>\n");
      out.write("			<p>가구</p>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"joongoMenuBox\">\n");
      out.write("			<button class=\"joongoMenuBtn menuBtn\">\n");
      out.write("				<img alt=\"\" src=\"/resources/image/baby_shark.png\" class=\"menuBtn\">\n");
      out.write("			</button>\n");
      out.write("			<p>유아동</p>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"joongoMenuBox\">\n");
      out.write("			<button class=\"joongoMenuBtn menuBtn\">\n");
      out.write("				<img alt=\"\" src=\"/resources/image/woman.png\" class=\"menuBtn\">\n");
      out.write("			</button>\n");
      out.write("			<p>여성의류</p>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"joongoMenuBox\">\n");
      out.write("			<button class=\"joongoMenuBtn menuBtn\">\n");
      out.write("				<img alt=\"\" src=\"/resources/image/man.png\" class=\"menuBtn\">\n");
      out.write("			</button>\n");
      out.write("			<p>남성의류</p>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"joongoMenuBox\">\n");
      out.write("			<button class=\"joongoMenuBtn menuBtn\">\n");
      out.write("				<img alt=\"\" src=\"/resources/image/iron.png\" class=\"menuBtn\">\n");
      out.write("			</button>\n");
      out.write("			<p>생활가전</p>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"joongoMenuBox\">\n");
      out.write("			<button class=\"joongoMenuBtn menuBtn\">\n");
      out.write("				<img alt=\"\" src=\"/resources/image/plate.png\" class=\"menuBtn\">\n");
      out.write("			</button>\n");
      out.write("			<p>생활|주방</p>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"joongoMenuBox\">\n");
      out.write("			<button class=\"joongoMenuBtn menuBtn\">\n");
      out.write("				<img alt=\"\" src=\"/resources/image/cookie.png\" class=\"menuBtn\">\n");
      out.write("			</button>\n");
      out.write("			<p>가공식품</p>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"joongoMenuBox\">\n");
      out.write("			<button class=\"joongoMenuBtn menuBtn\">\n");
      out.write("				<img alt=\"\" src=\"/resources/image/sunglasses.png\" class=\"menuBtn\">\n");
      out.write("			</button>\n");
      out.write("			<p>스포츠|레저</p>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"joongoMenuBox\">\n");
      out.write("			<button class=\"joongoMenuBtn menuBtn\">\n");
      out.write("				<img alt=\"\" src=\"/resources/image/joystick.png\" class=\"menuBtn\">\n");
      out.write("			</button>\n");
      out.write("			<p>취미|게임|음반</p>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"joongoMenuBox\">\n");
      out.write("			<button class=\"joongoMenuBtn menuBtn\">\n");
      out.write("				<img alt=\"\" src=\"/resources/image/brush.png\" class=\"menuBtn\">\n");
      out.write("			</button>\n");
      out.write("			<p>뷰티|미용</p>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"joongoMenuBox\">\n");
      out.write("			<button class=\"joongoMenuBtn menuBtn\">\n");
      out.write("				<img alt=\"\" src=\"/resources/image/green_leaves.png\" class=\"menuBtn\">\n");
      out.write("			</button>\n");
      out.write("			<p>식물</p>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"joongoMenuBox\">\n");
      out.write("			<button class=\"joongoMenuBtn menuBtn\">\n");
      out.write("				<img alt=\"\" src=\"/resources/image/dog.png\" class=\"menuBtn\">\n");
      out.write("			</button>\n");
      out.write("			<p>반려동물용품</p>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"joongoMenuBox\">\n");
      out.write("			<button class=\"joongoMenuBtn menuBtn\">\n");
      out.write("				<img alt=\"\" src=\"/resources/image/book.png\" class=\"menuBtn\">\n");
      out.write("			</button>\n");
      out.write("			<p>도서</p>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"joongoMenuBox\">\n");
      out.write("			<button class=\"joongoMenuBtn menuBtn\">\n");
      out.write("				<img alt=\"\" src=\"/resources/image/avocartLogo.png\" class=\"menuBtn\">\n");
      out.write("			</button>\n");
      out.write("			<p>기타</p>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<!-- 1번째 bodyContainer -->\n");
      out.write("\n");
      out.write("<!-- 중간 배너 -->\n");
      out.write("<div class=\"secondBanner\">\n");
      out.write("	<img alt=\"\" src=\"/resources/image/bannerTest1.jpg\">\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- bodyContainer 2 -->\n");
      out.write("<div class=\"bodyContainer\">\n");
      out.write("<!-- 동네업체 라인 -->\n");
      out.write("<div class=\"boardListLine storeListLine\">\n");
      out.write("	<div class=\"ListLineTop\">\n");
      out.write("		<p>우리 동네 인기 업체</p>\n");
      out.write("		<a href=\"/store/list\">더보기</a>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"ListLineMiddle\" id=\"storeMiddle\">\n");
      out.write("		<div class=\"store_item\">\n");
      out.write("			<a href=\"#\">\n");
      out.write("				<div class=\"store_item_img\">\n");
      out.write("					<img alt=\"\" src=\"\">\n");
      out.write("				</div>\n");
      out.write("				<div class=\"store_item_detail\">\n");
      out.write("					<p>멍이네</p>\n");
      out.write("					<p>강아지 미용합니다!</p>\n");
      out.write("					<p>구월동 | 반려동물 | 후기 3개</p>\n");
      out.write("				</div>\n");
      out.write("			</a>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- 알바구인 라인 -->\n");
      out.write("<div class=\"boardListLine jobNcmListTopMargin\">\n");
      out.write("	<div class=\"ListLineTop\">\n");
      out.write("		<p>우리 동네 인기 알바</p>\n");
      out.write("		<a href=\"/job/list\">더보기</a>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"ListLineMiddle\" id=\"jobMiddle\">\n");
      out.write("		<div class=\"job_item\">\n");
      out.write("			<a href=\"#\">\n");
      out.write("				<div class=\"job_item_img\">\n");
      out.write("					<img alt=\"\" src=\"\">\n");
      out.write("				</div>\n");
      out.write("				<div class=\"job_item_detail\">\n");
      out.write("					<p>제목</p>\n");
      out.write("					<p>위치</p>\n");
      out.write("					<p>가격</p>\n");
      out.write("				</div>\n");
      out.write("			</a>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- 동네소식 최신순 -->\n");
      out.write("<div class=\"boardListLine jobNcmListTopMargin\">\n");
      out.write("	<div class=\"ListLineTop\">\n");
      out.write("		<p>최신 동네 소식</p>\n");
      out.write("		<a href=\"/community/list\">더보기</a>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"ListLineMiddle\" id=\"communityMiddle\">\n");
      out.write("		<div class=\"community_list\">\n");
      out.write("			<a href=\"#\">\n");
      out.write("				<div class=\"cm_first\">\n");
      out.write("					<span>질문</span>\n");
      out.write("					<p>호떡차 어디에서 오는지 아시나요?</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"cm_second\">\n");
      out.write("					<span>구월동</span>\n");
      out.write("					<i class=\"bi bi-heart\"></i>\n");
      out.write("					<span>5 </span>\n");
      out.write("					<i class=\"bi bi-chat-right-dots\"></i>\n");
      out.write("					<span>10</span>\n");
      out.write("				</div>\n");
      out.write("			</a>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("<!-- 동네소식 인기순 -->\n");
      out.write("<div class=\"boardListLine cmLikeListLine\">\n");
      out.write("	<div class=\"ListLineTop\">\n");
      out.write("		<p>지금 뜨는 인기글</p>\n");
      out.write("		<a href=\"/community/list\">더보기</a>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"ListLineMiddle\" id=\"communityLikeMiddle\">\n");
      out.write("		<div class=\"community_list\">\n");
      out.write("			<a href=\"#\">\n");
      out.write("				<div class=\"cm_first\">\n");
      out.write("					<span>질문</span>\n");
      out.write("					<p>호떡차 어디에서 오는지 아시나요?</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"cm_second\">\n");
      out.write("					<span>구월동</span>\n");
      out.write("					<i class=\"bi bi-heart\"></i>\n");
      out.write("					<span>5 </span>\n");
      out.write("					<i class=\"bi bi-chat-right-dots\"></i>\n");
      out.write("					<span>10</span>\n");
      out.write("				</div>\n");
      out.write("			</a>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<!-- 여기까지 bodyContainer -->\n");
      out.write("<!-- 앱스토어 배너 -->\n");
      out.write("<div class=\"appStoreLine\">\n");
      out.write("	<div class=\"appStoreInner\">\n");
      out.write("		<p>당신 근처의 <br> 지역 생활 커뮤니티 </p>\n");
      out.write("		<p>동네라서 가능한 모든 것<br> 아보카트에서 가까운 이웃과 함께해요.</p>\n");
      out.write("		<a href=\"https://play.google.com/store/apps?hl=ko-KR\">\n");
      out.write("			<button type=\"button\"><i class=\"bi bi-google-play\"></i> Google Play</button>\n");
      out.write("		</a>\n");
      out.write("		<a href=\"https://apps.apple.com/kr/charts/iphone\">\n");
      out.write("			<button type=\"button\"><i class=\"bi bi-apple\"></i> App Store</button>\n");
      out.write("		</a>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./common/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/index.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
