/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-12-24 13:29:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.store;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Store Register</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/StoreBoardRegister.css\">\n");
      out.write("<style type=\"text/css\">\n");
      out.write(".hidden {\n");
      out.write("	display: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#proDetailAddr{\n");
      out.write("	border-left: none;\n");
      out.write("	border-top-left-radius: 0;\n");
      out.write("	border-bottom-left-radius: 0;\n");
      out.write("	width: 301.9px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>        \n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\n");
      out.write("<div class=\"storeBanner\">\n");
      out.write("     <div class=\"innerDiv\"></div>\n");
      out.write("</div>\n");
      out.write("<div class=\"bodyContainer\">\n");
      out.write("<div class=\"formLine\">\n");
      out.write("<form action=\"/store/register\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("	<input type=\"hidden\" name=\"proCategory\" value=\"store\">\n");
      out.write("    <div class=\"form\">\n");
      out.write("    	<p class=\"label\">제목</p>\n");
      out.write("		<input type=\"text\" name=\"proTitle\" id=\"proTitle\" class=\"titleInput\" placeholder=\"제목을 입력해 주세요\" required=\"required\">\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<div class=\"form\">\n");
      out.write("		<p class=\"label\">카테고리</p>\n");
      out.write("		<select name=\"proMenu\" id=\"proMenu\" class=\"cmMenu\">\n");
      out.write("		   <option value=\"선택\" selected style=\"display:none\">선택</option>\n");
      out.write("		   <option value=\"과외/클래스\">과외/클래스</option>\n");
      out.write("		   <option value=\"반려동물\">반려동물</option>\n");
      out.write("		   <option value=\"병원/약국\">병원/약국</option>\n");
      out.write("		   <option value=\"뷰티샵\">뷰티샵</option>\n");
      out.write("		   <option value=\"세탁소\">세탁소</option>\n");
      out.write("		   <option value=\"수리\">수리</option>\n");
      out.write("		   <option value=\"운동\">운동</option>\n");
      out.write("		   <option value=\"육아\">육아</option>\n");
      out.write("		   <option value=\"음식점\">음식점</option>\n");
      out.write("		   <option value=\"이사/용달\">이사/용달</option>\n");
      out.write("		   <option value=\"인테리어 시공\">인테리어 시공</option>\n");
      out.write("		   <option value=\"청소\">청소</option>\n");
      out.write("		   <option value=\"취미\">취미</option>\n");
      out.write("		   <option value=\"카페/디저트\">카페/디저트</option>\n");
      out.write("	    </select>\n");
      out.write("	</div>\n");
      out.write("    \n");
      out.write("	<div class=\"form\">\n");
      out.write("		<p class=\"label\">내용</p>\n");
      out.write("		<textarea id=\"dynamicTextarea\" name=\"proContent\" id=\"content\" class=\"contentInput\" placeholder=\"동네 이웃을 대상으로 우리 업체를 소개해 주세요\"  required=\"required\"></textarea>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	<!-- 지도 영역 -->\n");
      out.write("	<div class=\"form\">\n");
      out.write("	<p class=\"label\">지도</p>\n");
      out.write("	<div class=\"form fileForm\">\n");
      out.write("		<input type=\"text\" name=\"proFullAddr\" id=\"proFullAddr\" readonly=\"readonly\" class=\"fileInput\" placeholder=\"우리 업체의 주소를 등록해 주세요\"> \n");
      out.write("		<input name=\"proDetailAddr\" id=\"proDetailAddr\" class=\"fileInput hidden\" placeholder=\"상세 주소\"> \n");
      out.write("		<button type=\"button\" id=\"addr\" class=\"fileBtn\">주소추가</button>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	<div id=\"map\" style=\"width:100%;height:250px;\"></div>\n");
      out.write("	<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=d0bcf962e4604f2fbb0f443f01d101a4&libraries=services\"></script>\n");
      out.write("	<script>\n");
      out.write("	var mapContainer = document.getElementById('map'); //지도를 표시할 div \n");
      out.write("	var mapOption = {\n");
      out.write("	    center: new kakao.maps.LatLng(37.450292, 126.702921), //지도의 중심좌표\n");
      out.write("	    level: 3 //지도의 확대 레벨\n");
      out.write("	};  \n");
      out.write("	\n");
      out.write("	//지도 생성\n");
      out.write("	var map = new kakao.maps.Map(mapContainer, mapOption); \n");
      out.write("	\n");
      out.write("	//기본 마커 변경\n");
      out.write("	var imageSrc = '/resources/image/marker.png';\n");
      out.write("	var imageSize = new kakao.maps.Size(50, 55);\n");
      out.write("	var imageOption = {offset: new kakao.maps.Point(23, 55)};\n");
      out.write("	\n");
      out.write("	//마커 이미지 생성\n");
      out.write("	var markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize, imageOption),\n");
      out.write("	markerPosition = new kakao.maps.LatLng(37.450292, 126.702921); //마커 표시 위치(기본 위치)\n");
      out.write("	\n");
      out.write("	//마커 생성\n");
      out.write("	var marker = new kakao.maps.Marker({\n");
      out.write("	    position: markerPosition, \n");
      out.write("	    image: markerImage //마커이미지 설정 \n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	//지도 위 마커 표시\n");
      out.write("	marker.setMap(map);  	\n");
      out.write("	\n");
      out.write("	//입력 주소-좌표 변환 객체 생성\n");
      out.write("	var geocoder = new kakao.maps.services.Geocoder();\n");
      out.write("	\n");
      out.write("	//주소 좌표 검색\n");
      out.write("	function searchAndDisplay() {\n");
      out.write("        document.getElementById('proDetailAddr').value = '';\n");
      out.write("	    var address = document.getElementById('addr').value;\n");
      out.write("	    \n");
      out.write("	    //주소 값이 null이 아닌 경우에만 실행\n");
      out.write("	    if (address) {\n");
      out.write("	    	marker.setMap(null);\n");
      out.write("	    	\n");
      out.write("	        //주소로 좌표 검색\n");
      out.write("	        geocoder.addressSearch(address, function(result, status) {\n");
      out.write("	            //정상적으로 검색 완료됐으면 \n");
      out.write("	            if (status === kakao.maps.services.Status.OK) {\n");
      out.write("	                var coords = new kakao.maps.LatLng(result[0].y, result[0].x);\n");
      out.write("	\n");
      out.write("	                //결과값으로 받은 위치를 마커로 표시\n");
      out.write("	                marker = new kakao.maps.Marker({\n");
      out.write("	                    map: map,\n");
      out.write("	                    position: coords,\n");
      out.write("	                    image: markerImage\n");
      out.write("	                });\n");
      out.write("	\n");
      out.write("	                //지도의 중심을 결과값으로 받은 위치로 이동\n");
      out.write("	                map.setCenter(coords);\n");
      out.write("	                \n");
      out.write("	             	//proFullAddr 요소 값을 변경\n");
      out.write("	             	document.getElementById('proFullAddr').style.width = '301.9px';\n");
      out.write("	                document.getElementById('proFullAddr').value = address;\n");
      out.write("	                proDetailAddr.classList.remove('hidden');	            \n");
      out.write("	            }\n");
      out.write("	        });\n");
      out.write("	    }\n");
      out.write("	}\n");
      out.write("	</script>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	<p class=\"label\">메뉴</p>\n");
      out.write("	<div class=\"form fileForm\">\n");
      out.write("		<input type=\"text\" readonly=\"readonly\" class=\"fileInput\" placeholder=\"우리 업체의 메뉴를 등록해 주세요\"> \n");
      out.write("		<button type=\"button\" id=\"addMenu\" class=\"fileBtn\">메뉴추가</button>\n");
      out.write("	</div>\n");
      out.write("	<!-- 메뉴 영역 -->\n");
      out.write("	<div class=\"menuZone\" id=\"menuZone\" style=\"display:none\">\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<!-- 파일 -->\n");
      out.write("	<p class=\"label imgLabel\">이미지</p>\n");
      out.write("	<div class=\"form fileForm\">\n");
      out.write("		<input type=\"file\" class=\"form-control\" name=\"files\" id=\"files\" multiple=\"multiple\" style=\"display:none;\">\n");
      out.write("		<input type=\"text\" readonly=\"readonly\" class=\"fileInput\" placeholder=\"20MB 미만의 이미지를 업로드 해주세요\"> \n");
      out.write("		<button type=\"button\" id=\"trigger\" class=\"fileBtn\">파일첨부</button>\n");
      out.write("	</div>\n");
      out.write("	<!-- 첨부파일 표시 영역 -->\n");
      out.write("	<div class=\"fileZone\" id=\"fileZone\" style=\"display:none\">\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	<div class=\"cmButtons\">\n");
      out.write("		<a href=\"/store/list\"><button type=\"button\" class=\"cancelBtn\">취소</button></a>\n");
      out.write("		<button type=\"submit\" class=\"regBtn\" id=\"regBtn\" disabled=\"disabled\">작성하기</button>\n");
      out.write("	</div>\n");
      out.write("</form>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("let selectedAddress = '';\n");
      out.write("//지도 api\n");
      out.write("document.getElementById('addr').addEventListener('click', ()=>{\n");
      out.write("    //카카오 지도 발생\n");
      out.write("    new daum.Postcode({\n");
      out.write("        oncomplete: function(data) { //선택시 입력값 세팅\n");
      out.write("            console.log(data.address);\n");
      out.write("            selectedAddress = data.address;\n");
      out.write("            document.getElementById('addr').value = data.address;\n");
      out.write("            // 주소가 설정되자마자 검색 함수 호출\n");
      out.write("            searchAndDisplay();\n");
      out.write("            checkFields();\n");
      out.write("        }\n");
      out.write("    }).open();\n");
      out.write("});\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/storeBoardRegister.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/abjustTextareaRows.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
